apiVersion: extensions/v1beta1
kind: DaemonSet 
metadata:
  name: add-static-route
  namespace: default
spec:
  template:
    metadata:
      name: add-static-route
      labels:
        name: add-static-route
    spec:
      hostNetwork: true
      containers:
        - name: add-static-route
          image: ibmcase/kubectl
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c" ]
          args:
          - >
              while 
                _routes=`kubectl get configmap static-routes -o go-template --template '{{.data.routes}}' | jq 'join(" ")' | sed -e 's/"//g'`;
                _gateway=`ip route get 10.0.0.0/8 | sed 's/.*via \(.*\) dev.*/\1/'`;
                for _route in ${_routes}; do
                  [ -z "`ip route show | grep ${_route} | grep ${_gateway}`" ] || continue; 
                  echo "Adding ${_route} via ${_gateway} ...";
                  ip route add ${_route} via ${_gateway};
                done;
              do
                sleep 30;
              done
          securityContext:
            capabilities:
              add:
              - NET_ADMIN

